### ISSUE TITLE
Add keyboard navigation to in-post tabs

### ISSUE THREAD

**Issue by sybrew** [sybrew/the-seo-framework#283]
The in-post navigational tabs' radio buttons are currently set at `display:none`, this means they can't be focused.

https://github.com/sybrew/the-seo-framework/blob/366c157e759ebb5c73da27908f0120033598566f/lib/css/tsf.css#L847-L855

What we need:
1. Enable keyboard navigation by removing display:none, and setting the values below<sup>1</sup>. 
2. Highlight that there's focus on the tabs.

_<sup>1</sup> `display:none` alternative that allows focus:_
```css
input[type="radio"].tsf-flex-nav-tab-radio { 
	position: absolute;
	width: 0;
	height: 0;
	opacity: 0;
	margin: 0;
	padding: 0;
	border: 0;
	z-index: -1;
	-webkit-appearance: none;
	-moz-appearance: none;
	appearance: none;
}
```

This issue also accounts for the tabs in the settings area. Those will be looked at too.
