### ISSUE TITLE
Improved LTR support

### ISSUE THREAD

**Issue by sybrew** [sybrew/the-seo-framework#288]
Because URLs are always left to right, `#autodescription_canonical` should have the following CSS applied:
```css
#autodescription_canonical {
	direction: ltr;
}
```

We might also want to implement such behavior on the title, to alleviate `if/else` stacks.
